name: CI

on:
  push:
    branches:
      - master
      - v2.*
  pull_request:
    types: [opened, synchronize, reopened, edited]

env:
  LANG: C.UTF-8
  MESON_TESTTHREADS: 1

jobs:
  architectures:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [s390x]
        distro: [ubuntu20.04]
        buildtype: [debugoptimized, release]

    steps:
      - uses: actions/checkout@v2
        with:
          repository: hse-project/hse
    
      - name: Run on QEMU s390x
        uses: uraimo/run-on-arch-action@v2.1.1
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          dockerRunArgs: |
            --volume "${{github.workspace}}:/workspace"
          install: |
            apt-get update -y
            apt-get install -y build-essential libbsd-dev pkg-config openjdk-8-jdk libmicrohttpd-dev liburcu-dev libyaml-dev liblz4-dev libcurl4-openssl-dev python3-setuptools \ 
              libmongoc-1.0-0 libbson-1.0-0 libssl-dev libsasl2-dev python3-pip
            curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3
            . $HOME/.poetry/env
            poetry install       

          configure-build: |
           . $HOME/.poetry/env
           poetry run meson builddir -Dbuildtype=${{ matrix.buildtype }} --fatal-meson-warnings -Dycsb=true
          compile: |
            . $HOME/.poetry/env
            poetry run ninja -C builddir
          test: |
            . $HOME/.poetry/env
            poetry run meson test -C /workspace/builddir --setup=ci --print-errorlogs --no-stdsplit

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: build-artifact-${{ matrix.arch }}-${{ matrix.distro }}-${{ matrix.buildtype }}
          path: builddir/meson-logs/
